version: '2'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongo
    working_dir: /usr/src/app
    env_file: secrets.env
  mongo:
    image: mongo:3
    volumes:
      - /data/db
